UPDATE: Git-related scripts now check for `git` before running

diff --git a/bin-linux/git_compare_dates b/bin-linux/git_compare_dates
--- a/bin-linux/git_compare_dates
+++ b/bin-linux/git_compare_dates
@@ -89,6 +89,10 @@ gcd-results() {
 }
 
 main() {
+    if ! [[ "$(command -v git)" ]]; then
+        error "[ERROR]: Git does not appear to be installed. Exiting now."
+    fi
+
     check-git-repo
 
     gcd-loop
diff --git a/bin-linux/git_package_manager b/bin-linux/git_package_manager
--- a/bin-linux/git_package_manager
+++ b/bin-linux/git_package_manager
@@ -108,6 +108,10 @@ gpm-results() {
 }
 
 main() {
+    if ! [[ "$(command -v git)" ]]; then
+        error "[ERROR]: Git does not appear to be installed. Exiting now."
+    fi
+
     not_dirs=()
     dirs_not_repos=()
     repos_bad_fetch=()
